/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportRouteImport } from './routes/import'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as RecipesRecipeIdCookRouteImport } from './routes/recipes.$recipeId.cook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdCookRoute = RecipesRecipeIdCookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/import' | '/recipes/$recipeId' | '/recipes/$recipeId/cook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/import' | '/recipes/$recipeId' | '/recipes/$recipeId/cook'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/recipes/$recipeId'
    | '/recipes/$recipeId/cook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/cook': {
      id: '/recipes/$recipeId/cook'
      path: '/cook'
      fullPath: '/recipes/$recipeId/cook'
      preLoaderRoute: typeof RecipesRecipeIdCookRouteImport
      parentRoute: typeof RecipesRecipeIdRoute
    }
  }
}

interface RecipesRecipeIdRouteChildren {
  RecipesRecipeIdCookRoute: typeof RecipesRecipeIdCookRoute
}

const RecipesRecipeIdRouteChildren: RecipesRecipeIdRouteChildren = {
  RecipesRecipeIdCookRoute: RecipesRecipeIdCookRoute,
}

const RecipesRecipeIdRouteWithChildren = RecipesRecipeIdRoute._addFileChildren(
  RecipesRecipeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
